export const generatedEmployees = [
  {
    "firstName": "Muhammad",
    "lastName": "Cesar",
    "startDate": "1988-07-30",
    "department": "Human Resources",
    "birthDate": "1969-12-03",
    "state": "KY",
    "street": "Pennsylvania Ave",
    "city": "Richmond",
    "zipCode": 63368
  },
  {
    "firstName": "Magdalena",
    "lastName": "Rakesh",
    "startDate": "2023-01-31",
    "department": "Marketing",
    "birthDate": "2001-01-18",
    "state": "IL",
    "street": "Roxbury Dr",
    "city": "Cincinnati",
    "zipCode": 48104
  },
  {
    "firstName": "Viktor",
    "lastName": "Dora",
    "startDate": "1983-02-03",
    "department": "Engineering",
    "birthDate": "1961-04-26",
    "state": "WA",
    "street": "Santa Monica Blvd",
    "city": "Phoenix",
    "zipCode": 50315
  },
  {
    "firstName": "Abdullah",
    "lastName": "Agnes",
    "startDate": "2013-07-12",
    "department": "Engineering",
    "birthDate": "1982-07-01",
    "state": "NV",
    "street": "Laurel Canyon Blvd",
    "city": "Las Vegas",
    "zipCode": 48104
  },
  {
    "firstName": "Fabio",
    "lastName": "Ngoc",
    "startDate": "2020-10-19",
    "department": "Marketing",
    "birthDate": "1994-07-23",
    "state": "IN",
    "street": "Fifth St",
    "city": "Fresno",
    "zipCode": 27526
  },
  {
    "firstName": "Sabina",
    "lastName": "Wei",
    "startDate": "2007-07-20",
    "department": "Human Resources",
    "birthDate": "1966-03-16",
    "state": "IA",
    "street": "Pennsylvania Ave",
    "city": "Fort Worth",
    "zipCode": 94066
  },
  {
    "firstName": "Sharmin",
    "lastName": "Kavita",
    "startDate": "2019-07-22",
    "department": "Sales",
    "birthDate": "1986-03-18",
    "state": "TN",
    "street": "Beverly Crest Dr",
    "city": "Atlanta",
    "zipCode": 87507
  },
  {
    "firstName": "Stella",
    "lastName": "Tatyana",
    "startDate": "2003-01-24",
    "department": "Human Resources",
    "birthDate": "1982-01-03",
    "state": "MT",
    "street": "Mulholland Dr",
    "city": "Jersey City",
    "zipCode": 91381
  },
  {
    "firstName": "Kelly",
    "lastName": "Michelle",
    "startDate": "2023-11-13",
    "department": "Marketing",
    "birthDate": "2005-11-07",
    "state": "DE",
    "street": "Franklin Ave",
    "city": "Reno",
    "zipCode": 60005
  },
  {
    "firstName": "Shanshan",
    "lastName": "Iman",
    "startDate": "2021-03-13",
    "department": "Human Resources",
    "birthDate": "2002-04-22",
    "state": "DE",
    "street": "Melrose Ave",
    "city": "San Francisco",
    "zipCode": 84032
  },
  {
    "firstName": "Ellen",
    "lastName": "Salim",
    "startDate": "2013-11-25",
    "department": "Sales",
    "birthDate": "1993-11-11",
    "state": "NV",
    "street": "Fairfax Ave",
    "city": "Winston-Salem",
    "zipCode": 75082
  },
  {
    "firstName": "Nina",
    "lastName": "Umesh",
    "startDate": "2012-06-22",
    "department": "Legal",
    "birthDate": "1987-06-19",
    "state": "CT",
    "street": "Winding Way",
    "city": "Cincinnati",
    "zipCode": 92612
  },
  {
    "firstName": "Jianmin",
    "lastName": "Alice",
    "startDate": "2006-04-20",
    "department": "Legal",
    "birthDate": "1976-03-08",
    "state": "NV",
    "street": "Canon Dr",
    "city": "Garland",
    "zipCode": 37857
  },
  {
    "firstName": "Luisa",
    "lastName": "Roland",
    "startDate": "1988-03-26",
    "department": "Legal",
    "birthDate": "1966-06-26",
    "state": "NH",
    "street": "Pico Blvd",
    "city": "Chesapeake",
    "zipCode": 94066
  },
  {
    "firstName": "Samira",
    "lastName": "Angelica",
    "startDate": "1989-10-20",
    "department": "Marketing",
    "birthDate": "1963-02-01",
    "state": "GA",
    "street": "Park Ave",
    "city": "Winston-Salem",
    "zipCode": 80246
  },
  {
    "firstName": "Wolfgang",
    "lastName": "Xin",
    "startDate": "2021-08-19",
    "department": "Engineering",
    "birthDate": "2002-07-21",
    "state": "CA",
    "street": "Ocean Blvd",
    "city": "Lexington",
    "zipCode": 60487
  },
  {
    "firstName": "Hawa",
    "lastName": "Saraswati",
    "startDate": "2009-12-27",
    "department": "Legal",
    "birthDate": "1977-09-24",
    "state": "MD",
    "street": "Lombard St",
    "city": "Columbus",
    "zipCode": 97405
  },
  {
    "firstName": "Joan",
    "lastName": "Bernard",
    "startDate": "2023-06-19",
    "department": "Sales",
    "birthDate": "1959-06-15",
    "state": "MN",
    "street": "Wilshire Blvd",
    "city": "Lexington",
    "zipCode": 38301
  },
  {
    "firstName": "Mustafa",
    "lastName": "Ramon",
    "startDate": "2022-09-25",
    "department": "Engineering",
    "birthDate": "2001-06-02",
    "state": "AS",
    "street": "Beach Ave",
    "city": "New York",
    "zipCode": 27203
  },
  {
    "firstName": "Santosh",
    "lastName": "Valerie",
    "startDate": "2002-09-23",
    "department": "Marketing",
    "birthDate": "1971-01-13",
    "state": "NE",
    "street": "Lombard St",
    "city": "Phoenix",
    "zipCode": 94066
  },
  {
    "firstName": "Eva",
    "lastName": "Shobha",
    "startDate": "2001-09-11",
    "department": "Marketing",
    "birthDate": "1982-11-25",
    "state": "CO",
    "street": "Western Ave",
    "city": "Philadelphia",
    "zipCode": 77802
  },
  {
    "firstName": "Hai",
    "lastName": "Nathalie",
    "startDate": "2023-07-09",
    "department": "Human Resources",
    "birthDate": "1962-09-25",
    "state": "TX",
    "street": "North Rd",
    "city": "Gilbert",
    "zipCode": 48104
  },
  {
    "firstName": "Alaa",
    "lastName": "Khaled",
    "startDate": "2020-03-27",
    "department": "Sales",
    "birthDate": "2000-06-23",
    "state": "MO",
    "street": "Washington Blvd",
    "city": "Saint Paul",
    "zipCode": 52401
  },
  {
    "firstName": "Santosh",
    "lastName": "Vladimir",
    "startDate": "2021-04-30",
    "department": "Human Resources",
    "birthDate": "1993-02-25",
    "state": "SD",
    "street": "Atlantic Ave",
    "city": "Oklahoma City",
    "zipCode": 45431
  },
  {
    "firstName": "Tien",
    "lastName": "Karl",
    "startDate": "2019-02-10",
    "department": "Sales",
    "birthDate": "1994-03-14",
    "state": "ME",
    "street": "Canyon Dr",
    "city": "Minneapolis",
    "zipCode": 60187
  },
  {
    "firstName": "Yanhong",
    "lastName": "Aziz",
    "startDate": "2019-04-11",
    "department": "Sales",
    "birthDate": "1996-05-16",
    "state": "MN",
    "street": "Broad St",
    "city": "Scottsdale",
    "zipCode": 98121
  },
  {
    "firstName": "Kseniya",
    "lastName": "Yanping",
    "startDate": "2020-06-16",
    "department": "Engineering",
    "birthDate": "1992-01-28",
    "state": "NV",
    "street": "Outpost Dr",
    "city": "Norfolk",
    "zipCode": 42001
  },
  {
    "firstName": "Aida",
    "lastName": "Jacques",
    "startDate": "2016-01-07",
    "department": "Engineering",
    "birthDate": "1981-03-21",
    "state": "IN",
    "street": "Crenshaw Blvd",
    "city": "San Francisco",
    "zipCode": 55306
  },
  {
    "firstName": "Chunhua",
    "lastName": "Ruben",
    "startDate": "2017-12-15",
    "department": "Human Resources",
    "birthDate": "1964-07-21",
    "state": "NE",
    "street": "Pico Blvd",
    "city": "Chesapeake",
    "zipCode": 37857
  },
  {
    "firstName": "Jeffrey",
    "lastName": "Rajendra",
    "startDate": "1989-08-12",
    "department": "Engineering",
    "birthDate": "1962-08-15",
    "state": "KS",
    "street": "Barrington Pl",
    "city": "Fremont",
    "zipCode": 38135
  },
  {
    "firstName": "Daniela",
    "lastName": "Man",
    "startDate": "2023-11-04",
    "department": "Engineering",
    "birthDate": "2000-06-11",
    "state": "WA",
    "street": "Barrington Pl",
    "city": "Buffalo",
    "zipCode": 38135
  },
  {
    "firstName": "Nina",
    "lastName": "Diana",
    "startDate": "2004-11-06",
    "department": "Human Resources",
    "birthDate": "1977-01-02",
    "state": "WA",
    "street": "Overland Ave",
    "city": "Denver",
    "zipCode": 97070
  },
  {
    "firstName": "Sam",
    "lastName": "Sima",
    "startDate": "1999-07-21",
    "department": "Human Resources",
    "birthDate": "1972-06-19",
    "state": "IN",
    "street": "San Vicente Blvd",
    "city": "Fort Worth",
    "zipCode": 27526
  },
  {
    "firstName": "Uma",
    "lastName": "Rashid",
    "startDate": "2017-09-16",
    "department": "Human Resources",
    "birthDate": "1997-07-14",
    "state": "DE",
    "street": "Ventura Blvd",
    "city": "Saint Paul",
    "zipCode": 60608
  },
  {
    "firstName": "Imran",
    "lastName": "Peng",
    "startDate": "2007-07-01",
    "department": "Legal",
    "birthDate": "1959-03-02",
    "state": "AL",
    "street": "Broad St",
    "city": "Hialeah",
    "zipCode": 75104
  },
  {
    "firstName": "Tuan",
    "lastName": "Tadesse",
    "startDate": "2022-09-25",
    "department": "Legal",
    "birthDate": "2001-06-02",
    "state": "WI",
    "street": "Sunset Strip",
    "city": "Santa Ana",
    "zipCode": 92821
  },
  {
    "firstName": "Viktor",
    "lastName": "Sarah",
    "startDate": "2020-07-10",
    "department": "Sales",
    "birthDate": "1995-01-18",
    "state": "HI",
    "street": "Ventura Canyon Ave",
    "city": "Seattle",
    "zipCode": 94588
  },
  {
    "firstName": "Javier",
    "lastName": "Sandra",
    "startDate": "2004-05-20",
    "department": "Engineering",
    "birthDate": "1983-01-20",
    "state": "DE",
    "street": "Western Ave",
    "city": "Chula Vista",
    "zipCode": 96761
  },
  {
    "firstName": "Nicholas",
    "lastName": "Tomasz",
    "startDate": "2011-03-03",
    "department": "Engineering",
    "birthDate": "1984-04-18",
    "state": "FM",
    "street": "Washington Blvd",
    "city": "Irving",
    "zipCode": 95050
  },
  {
    "firstName": "Hossein",
    "lastName": "Susana",
    "startDate": "2009-05-26",
    "department": "Engineering",
    "birthDate": "1970-12-27",
    "state": "NC",
    "street": "Ventura Canyon Ave",
    "city": "Denver",
    "zipCode": 50010
  },
  {
    "firstName": "Evgeniy",
    "lastName": "Marilyn",
    "startDate": "2000-09-28",
    "department": "Engineering",
    "birthDate": "1978-09-19",
    "state": "NC",
    "street": "Barrington Pl",
    "city": "San Bernardino",
    "zipCode": 60187
  },
  {
    "firstName": "Alice",
    "lastName": "Sushila",
    "startDate": "2016-08-10",
    "department": "Legal",
    "birthDate": "1973-09-25",
    "state": "IN",
    "street": "Mulholland Dr",
    "city": "Montgomery",
    "zipCode": 87507
  },
  {
    "firstName": "Paula",
    "lastName": "Jinhua",
    "startDate": "2001-10-18",
    "department": "Legal",
    "birthDate": "1969-01-07",
    "state": "FM",
    "street": "Main St",
    "city": "Newark",
    "zipCode": 80017
  },
  {
    "firstName": "Lila",
    "lastName": "Mai",
    "startDate": "2008-10-12",
    "department": "Sales",
    "birthDate": "1987-12-02",
    "state": "VI",
    "street": "Houston St",
    "city": "Houston",
    "zipCode": 14610
  },
  {
    "firstName": "Ran",
    "lastName": "Andre",
    "startDate": "2011-09-26",
    "department": "Marketing",
    "birthDate": "1968-11-24",
    "state": "WI",
    "street": "Wilshire Blvd",
    "city": "St. Petersburg",
    "zipCode": 77573
  },
  {
    "firstName": "Shan",
    "lastName": "Roland",
    "startDate": "2015-10-23",
    "department": "Legal",
    "birthDate": "1984-09-02",
    "state": "NC",
    "street": "Canal St",
    "city": "Orlando",
    "zipCode": 14063
  },
  {
    "firstName": "Gopal",
    "lastName": "Pamela",
    "startDate": "2023-02-02",
    "department": "Marketing",
    "birthDate": "2004-08-17",
    "state": "NC",
    "street": "Ventura Canyon Ave",
    "city": "Los Angeles",
    "zipCode": 94588
  },
  {
    "firstName": "Yin",
    "lastName": "Mai",
    "startDate": "2023-07-09",
    "department": "Marketing",
    "birthDate": "2003-01-25",
    "state": "WI",
    "street": "Ventura Blvd",
    "city": "Glendale",
    "zipCode": 80017
  },
  {
    "firstName": "Ingrid",
    "lastName": "Shahid",
    "startDate": "2009-12-27",
    "department": "Engineering",
    "birthDate": "1977-09-24",
    "state": "FM",
    "street": "Barrington Ave",
    "city": "Miami",
    "zipCode": 77573
  },
  {
    "firstName": "Ida",
    "lastName": "Lijun",
    "startDate": "2023-01-11",
    "department": "Legal",
    "birthDate": "1983-04-17",
    "state": "SC",
    "street": "Cahuenga Blvd",
    "city": "Lincoln",
    "zipCode": 50309
  }
]